server:
  port: 8081

spring:
  application:
    name: EUREKACLIENT
  main:
    allow-bean-definition-overriding: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR